### ISSUE TITLE
fastdist is sometimes slower than scipy.spatial.distance.cdist

### ISSUE THREAD

**Issue by moi90** [talboger/fastdist#2]
`fastdist.matrix_to_matrix_distance` is consistently slower than `scipy.spatial.distance.cdist`:

![grafik](https://user-images.githubusercontent.com/332746/95657386-99a65b80-0b14-11eb-97c8-774b03f7241e.png)

Code to replicate: https://gist.github.com/moi90/e16af9cbb82b62e07ecc143ca24dfe41

Am I using it wrong?

**Comment by talboger** [comment]
You're using it right. For smaller operations involving lower-dimensional matrices and vectors, scipy's implementation can be faster. However, as the required computation increases, fastidst becomes faster than scipy. For example, running your code with 1000 dimensions instead of 100 shows that fastdist is faster:

![fastdist_1000_euclidean](https://user-images.githubusercontent.com/61988768/95698461-005c6f80-0c10-11eb-967a-c067971b49ab.png)

This speed difference also depends on the distance being calculated (certain distance formulas are easier to optimize and speed up in numba). So, it's not always true that for 100 dimensions, fastdist will be slower than scipy. For example, if we use cosine similarity, we see that fastdist is consistently faster at 100 dimensions:

![fastdist_100_cosine](https://user-images.githubusercontent.com/61988768/95698494-1833f380-0c10-11eb-9038-1695c132903e.png)

**Comment by moi90** [comment]
Thanks for the explanation!

I think the cases where scipy is maybe faster should be mentioned in the documentation.

Maybe, the package could even include a command that enables a quick comparison for a specific use case (e.g. something like `python -m fastdist compare_speed --d=1000 --n=100000 --metric=cosine`).

**Comment by talboger** [comment]
Thanks for the suggestions!

I'll definitely look into adding a `compare_speed` function.

Determining a clean and concrete way to say where scipy is faster may be tricky. As we saw, this depends on the function and dimensions, making it hard to create firm boundaries. Potentially it could be as simple as "for operations involving more than _n_ elements with distance function _f_, fastdist is faster." However, it could be more complicated than that (e.g., maybe operating on longer/wider matrices is faster, creating a dependency on not just the number of elements but also the shape). I'll check if it's the former or the latter. If there are nice boundaries, it would make a lot of sense to add simple if statements that make us fall back on scipy implementations if we know they'll be faster.
