### ISSUE TITLE
Strange results from Jaccard function

### ISSUE THREAD

**Issue by saskra** [talboger/fastdist#8]
https://github.com/talboger/fastdist/blob/a22e2ca32a6b50d04178cd23b1d80632970d15e7/fastdist/fastdist.py#L610

Your implementation of the Jaccard index gives results which are not consistent with what I would expect:

```python
import numpy as np
from fastdist import fastdist
from sklearn import metrics

y_true = np.random.randint(2, size=10000)
y_pred = np.random.randint(2, size=10000)

js1 = fastdist.jaccard(y_true, y_pred)
print("Fastdist function: " + str(js1))
cm_fast = fastdist.confusion_matrix(y_true, y_pred)
tp, fn, fp, _ = cm_fast.ravel()
js2 = tp / (tp + fp + fn)
print("Original formula with fastdist CM: " + str(js2))
js3 = metrics.jaccard_score(y_true, y_pred, pos_label=0)
print("Sklearn function: " + str(js3))
cm_sk = metrics.confusion_matrix(y_true, y_pred)
tp, fn, fp, _ = cm_sk.ravel()
js4 = tp / (tp + fp + fn)
print("Original formula with sklearn CM: " + str(js4))
#
# Fastdist function: 0.656937225109956
# Original formula with fastdist CM: 0.33625100996498786
# Sklearn function: 0.33625100996498786
# Original formula with sklearn CM: 0.33625100996498786
```

**Comment by talboger** [comment]
Good question! My Jaccard function is not supposed to be the same as sklearn's. Distance functions are defined such that they'll give the same output as scipy.spatial.distance's versions, which ours succeeds in doing:

```python
import numpy as np
from fastdist import fastdist
from scipy.spatial import distance
from sklearn import metrics

y_true = np.random.randint(2, size=10000)
y_pred = np.random.randint(2, size=10000)

js1 = fastdist.jaccard(y_true, y_pred)
print("Fastdist function: " + str(js1))

js2 = distance.jaccard(y_true, y_pred)
print("Scipy function: " + str(js1))

# Fastdist function: 0.6549221430456584
# Scipy function: 0.6549221430456584
```

This is because of a slight difference in definition between the scipy/fastdist implementation and the sklearn implementation. First, sklearn measures the Jaccard similarity, while scipy/fastdist use jaccard dissimilarity. sklearn's does, as you did, tp / (tp + fp + fn) for Jaccard similarity. meanwhile, scipy/fastdist do (fp + fn) / (tn + fp + fn) for Jaccard dissimilarity, so for similarity, we'd do 1 - ((fp + fn) / (tn + fp + fn)), which is the same as tn / (tn + fp + fn). So, this means if you set pos_label=1 in sklearn's function, you will get the corresponding Jaccard similarity to the scipy/fastdist dissimilarity:

```python
js3 = jaccard_score(y_true, y_pred, pos_label=1)
print("Sklearn function: " + str(js3))
print("Sklearn dissimilarity: " + str(1 - js3))

# Sklearn function: 0.3450778569543415
# Sklearn dissimilarity: 0.3450778569543415
```

Hope that helps!

**Comment by saskra** [comment]
Thanks, then I can convert it now!
